### ISSUE TITLE
Bugs + Pheedback

### ISSUE THREAD

**Issue by apurvpandit** [aakashlpin/cheapass-ios-app#1]
- Verification called OTP on app and Verification Code on email. Follow same terminology? (Verification Code is preferable since thisis not exactly a _"one time password" created for a specific transaction that will expire in t=x_).
- It is not at all apparent in the design that I can swipe-left on the items to reveal the shopping cart icon. On the other hand, the Amazon badge looks like a button. My first instinct was to try and tap on that "button" but nothing happened. So I concluded that all that this app does is show the status of my preset alerts.
- I logged out back to the intro screen. My email was prefilled in the login box. I tapped next, my previously filled OTP was pre-filled too. I simultaneously received an email with the new OTP. However upon tapping next, I was able to login successfully via my older pre-filled OTP. If this is intentional, doesn't it make verification pointless?
- Tried the above again after logging out. Still able to log in with the original OTP, despite there being a new one in my email.
- Why not deep-link to the Amazon app on my phone instead of opening Amazon on mobile web?

**Comment by aakashlpin** [comment]
@apurvpandit thanks for the feedback. Most of the issues have been fixed now except making swipe-left apparent. Will fix it in the next version.

Cheers!
